name: Publish Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Clone&Copy Clice
        shell: bash
        run: |
          git clone https://github.com/clice-io/clice.git
          cp -a clice/docs/en/. ./en/clice/
          cp -a clice/docs/zh/. ./zh/clice/

      - name: Clone&Copy Catter
        shell: bash
        run: |
          git clone https://github.com/clice-io/catter.git
          cp -a catter/doc/. ./en/catter/
          cp -a catter/doc/. ./zh/catter/

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          keep_files: true
